# Configuration pour Go
---
version: 2 #la version de la configuration YAML utilisée ici est la version 2
updates:
  - package-ecosystem: "gomod" #configurer les mises à jour pour les dépendances Go
    directory: "/" #permet de mettre à jour les dépendances directes de type "minor" (les dépendances mineures).
    schedule:
      interval: "daily"
    allow:  #spécifie les types de mises à jour autorisées
      - dependency-type: "direct"
        update-type: "semver:minor" #la mise à jour des dépendances directes de type "minor" est autorisée

# Configuration pour Docker
---
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"