# Configuration du Go
---
version: 2 #la version utilisée pour la configuration est la 2
updates:
  - package-ecosystem: "gomod" #configurer les mises à jour pour les dépendances Go
    directory: "/" #permet ou mettre à jour les dépendances directes de type minor
    schedule:
      interval: "daily"
    allow:  #spécifie les types de mises à jour autorisées
      - dependency-type: "direct"
        update-type: "semver:minor" #la mise à jour des dépendances directes de type minor est autorisée

# Configuration du Docker
---
version: 2
updates:
  - package-ecosystem: "docker" #la mise à jour de conteneurs Docker
    directory: "/"
    schedule:
      interval: "daily" #la mise à jour doit se produire quotidiennement