name: Release Workflow
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
     actions: write
     checks: write
     contents: write
     deployments: write
     id-token: write
     issues: write
     pull-requests: write
     repository-projects: write
     security-events: write
     statuses: write
    steps:
      - uses: actions/checkout@v3 #pour récupérer le code
      - name: Set up Go
        uses: actions/setup-go@v4 # la configuration de Go
        with:
          go-version: stable
      - name: Build and Release
        uses: goreleaser/goreleaser-action@v4 # la création d'une release
        if: success() && startsWith(github.ref, 'refs/tags/') #vérifier si le push est sur tag et si le build a été succès avant de lancer le job de build et de release
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build And Publish Image
        uses: docker/build-push-action@v4 #la publication d'une image Docker sur Docker Hub
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/super_calculator:${{  github.ref_name }} #pour récupérer les infos d'identification Docker Hub et GitHub
          
